//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Control.proto
namespace Pika.Game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Control")]
  public partial class Control : global::ProtoBuf.IExtensible
  {
    public Control() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }

    private Pika.Game.Control.Status _Character = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Character", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Pika.Game.Control.Status Character
    {
      get { return _Character; }
      set { _Character = value; }
    }

    private Pika.Game.Control.Status _Ball = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Ball", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Pika.Game.Control.Status Ball
    {
      get { return _Ball; }
      set { _Ball = value; }
    }
    private Pika.Game.Control.MotionType _motion;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"motion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Pika.Game.Control.MotionType motion
    {
      get { return _motion; }
      set { _motion = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Status")]
  public partial class Status : global::ProtoBuf.IExtensible
  {
    public Status() {}
    
    private float _loc_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loc_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float loc_x
    {
      get { return _loc_x; }
      set { _loc_x = value; }
    }
    private float _loc_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"loc_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float loc_y
    {
      get { return _loc_y; }
      set { _loc_y = value; }
    }

    private float _vel_x = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vel_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float vel_x
    {
      get { return _vel_x; }
      set { _vel_x = value; }
    }

    private float _vel_y = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vel_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float vel_y
    {
      get { return _vel_y; }
      set { _vel_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MotionType")]
    public enum MotionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALK", Value=0)]
      WALK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JUMP", Value=1)]
      JUMP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SLIDE", Value=2)]
      SLIDE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPIKE", Value=3)]
      SPIKE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WIN", Value=4)]
      WIN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOSE", Value=5)]
      LOSE = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}